import type { Product, Recipe, Order } from './types';

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Chocolate Chip Cookies',
    description: 'Classic homemade chocolate chip cookies, crispy on the outside, chewy on the inside.',
    price: 12.00,
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    dataAiHint: 'chocolate chip cookies',
    category: 'Cookies',
    tags: ['Chocolate', 'Classic', 'Top Seller'],
    details: {
      contains: 'Wheat, Eggs, Dairy, Soy',
      prepTime: '24 hours',
      pricePer: 'per dozen',
    },
    packageTypes: [
      { id: 'pkg_plain', name: 'Plain Box', price: 0 },
      { id: 'pkg_gift', name: 'Gift Wrap', price: 5 },
      { id: 'pkg_bday', name: 'Birthday Box', price: 10 },
    ],
    hasRecipe: true,
    recipeId: 'rec_1',
  },
  {
    id: 'prod_2',
    name: 'Red Velvet Cupcakes',
    description: 'Moist red velvet cupcakes with a rich cream cheese frosting.',
    price: 24.00,
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    dataAiHint: 'red velvet cupcake',
    category: 'Cupcakes',
    tags: ['Classic', 'Cream Cheese'],
     details: {
      contains: 'Wheat, Eggs, Dairy',
      prepTime: '4 hours',
      pricePer: 'per 6 cupcakes',
    },
    packageTypes: [
      { id: 'pkg_plain', name: 'Plain Box', price: 0 },
      { id: 'pkg_gift', name: 'Gift Wrap', price: 5 },
    ],
    hasRecipe: true,
    recipeId: 'rec_2',
  },
  {
    id: 'prod_3',
    name: 'Classic Cheesecake',
    description: 'A creamy and delicious New York style cheesecake with a graham cracker crust.',
    price: 150.0,
    images: [
      'https://placehold.co/600x400.png'
    ],
    dataAiHint: 'cheesecake slice',
    category: 'Cakes',
    tags: ['Classic', 'Creamy', 'Top Seller'],
     details: {
      contains: 'Wheat, Eggs, Dairy',
      prepTime: '48 hours (pre-order)',
      pricePer: 'per 9" cake',
    },
    variations: [
        { id: 'var_plain', name: 'Plain', priceModifier: 0, inStock: true },
        { id: 'var_strawberry', name: 'Strawberry Topping', priceModifier: 15, inStock: true },
        { id: 'var_chocolate', name: 'Chocolate Drizzle', priceModifier: 10, inStock: false },
    ],
    hasRecipe: true,
    recipeId: 'rec_3',
  },
  {
    id: 'prod_4',
    name: 'Vegan Oatmeal Cookies',
    description: 'Hearty and sweet oatmeal raisin cookies spiced with cinnamon, completely plant-based.',
    price: 15.00,
    images: [
      'https://placehold.co/600x400.png',
    ],
    dataAiHint: 'oatmeal raisin cookies',
    category: 'Cookies',
    tags: ['Vegan', 'Non-Fat', 'Oatmeal'],
     details: {
      contains: 'Wheat, Oats (May contain traces of nuts)',
      prepTime: '8 hours',
      pricePer: 'per dozen',
    },
    hasRecipe: false,
  },
  {
    id: 'prod_5',
    name: 'Sourdough Bread',
    description: 'Artisanal sourdough bread with a crispy crust and a soft, airy crumb.',
    price: 30.00,
    images: [
      'https://placehold.co/600x400.png',
    ],
    dataAiHint: 'sourdough bread',
    category: 'Goods',
    tags: ['Vegan', 'Classic', 'Bread'],
     details: {
      prepTime: '48 hours',
      pricePer: 'per loaf',
    },
    hasRecipe: false,
  },
  {
    id: 'prod_6',
    name: 'Carrot Cake',
    description: 'A delightfully moist and flavorful carrot cake filled with nuts and topped with cream cheese frosting.',
    price: 160.0,
    images: [
      'https://placehold.co/600x400.png',
    ],
    dataAiHint: 'carrot cake',
    category: 'Cakes',
    tags: ['Classic', 'Nuts'],
     details: {
      contains: 'Wheat, Eggs, Dairy, Nuts',
      prepTime: '48 hours (pre-order)',
      pricePer: 'per 9" cake',
    },
    hasRecipe: true,
    recipeId: 'rec_4'
  },
];

export const recipes: Recipe[] = [
  {
    id: 'rec_1',
    productId: 'prod_1',
    name: 'Ultimate Chocolate Chip Cookies Recipe',
    description: 'The secret to the best chocolate chip cookies. This paid recipe gives you all the tips and tricks.',
    ingredients: [
      { name: 'All-purpose flour', quantity: '2 1/4 cups' },
      { name: 'Baking soda', quantity: '1 tsp' },
      { name: 'Salt', quantity: '1/2 tsp' },
      { name: 'Unsalted butter, melted', quantity: '3/4 cup' },
      { name: 'Brown sugar', quantity: '1 cup packed' },
      { name: 'White sugar', quantity: '1/2 cup' },
      { name: 'Vanilla extract', quantity: '1 tbsp' },
      { name: 'Egg', quantity: '1' },
      { name: 'Egg yolk', quantity: '1' },
      { name: 'Semisweet chocolate chips', quantity: '2 cups' },
    ],
    instructions: [
      'Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.',
      'Sift together the flour, baking soda, and salt; set aside.',
      'In a medium bowl, cream together the melted butter, brown sugar, and white sugar until well blended.',
      'Beat in the vanilla, egg, and egg yolk until light and creamy.',
      'Mix in the sifted ingredients until just blended. Stir in the chocolate chips.',
      'Drop cookie dough by large spoonfuls onto the prepared baking sheets.',
      'Bake for 15 to 17 minutes in the preheated oven, or until the edges are lightly toasted.',
      'Cool on baking sheets for a few minutes before transferring to wire racks to cool completely.',
    ],
    isPaid: true,
    price: 18.00,
    rating: 5,
    reviews: 120,
  },
  {
    id: 'rec_2',
    productId: 'prod_2',
    name: 'Perfect Red Velvet Cupcakes Recipe',
    description: 'Learn to make bakery-quality red velvet cupcakes at home with this simple recipe.',
    ingredients: [
      { name: 'All-purpose flour', quantity: '2 1/2 cups' },
      { name: 'Baking soda', quantity: '1 tsp' },
      { name: 'Unsweetened cocoa powder', quantity: '1 tbsp' },
      { name: 'Salt', quantity: '1/2 tsp' },
      { name: 'Buttermilk', quantity: '1 cup' },
      { name: 'Red food coloring', quantity: '2 tbsp' },
      { name: 'White vinegar', quantity: '1 tsp' },
      { name: 'Vanilla extract', quantity: '1 tsp' },
      { name: 'Unsalted butter, softened', quantity: '1/2 cup' },
      { name: 'Granulated sugar', quantity: '1 1/2 cups' },
      { name: 'Eggs', quantity: '2' },
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C) and line a muffin tin with cupcake liners.',
      'In a medium bowl, whisk together flour, baking soda, cocoa powder, and salt.',
      'In a separate small bowl, combine buttermilk, red food coloring, vinegar, and vanilla.',
      'In a large bowl, beat the butter and sugar with an electric mixer until light and fluffy. Add eggs one at a time, beating well after each addition.',
      'Alternate adding the flour mixture and the buttermilk mixture to the butter mixture, beginning and ending with the flour. Mix until just combined.',
      'Divide the batter among the cupcake liners, filling each about two-thirds full.',
      'Bake for 20 to 22 minutes, or until a toothpick inserted into the center comes out clean.',
      'Let cool in the pan for a few minutes before transferring to a wire rack to cool completely before frosting.',
    ],
    isPaid: false,
    price: 0,
    rating: 4.8,
    reviews: 250,
  },
  {
      id: 'rec_3',
      productId: 'prod_3',
      name: 'Decadent Classic Cheesecake Recipe',
      description: 'Unlock the secrets to a crack-free, creamy, and utterly decadent cheesecake. A must-have for any baker.',
      ingredients: [
          { name: 'Graham cracker crumbs', quantity: '1 1/2 cups' },
          { name: 'Sugar', quantity: '2 tbsp' },
          { name: 'Unsalted butter, melted', quantity: '1/3 cup' },
          { name: 'Cream cheese, softened', quantity: '4 (8-ounce) packages' },
          { name: 'Granulated sugar', quantity: '1 1/2 cups' },
          { name: 'All-purpose flour', quantity: '3 tbsp' },
          { name: 'Large eggs', quantity: '5' },
          { name: 'Heavy cream', quantity: '1/2 cup' },
          { name: 'Sour cream', quantity: '1/4 cup' },
          { name: 'Vanilla extract', quantity: '1 tbsp' },
      ],
      instructions: [
          'Preheat oven to 325°F (165°C). Wrap the outside of a 9-inch springform pan with a double layer of heavy-duty foil.',
          'For the crust, mix graham cracker crumbs, 2 tablespoons sugar, and melted butter. Press onto the bottom of the prepared pan.',
          'Bake crust for 10 minutes. Cool on a wire rack.',
          'For the filling, in a large bowl, beat cream cheese and 1 1/2 cups sugar until smooth. Beat in flour. Add eggs one at a time, mixing on low speed until just blended.',
          'Stir in heavy cream, sour cream, and vanilla.',
          'Pour filling over crust. Place the pan in a larger roasting pan. Add hot water to the roasting pan to come halfway up the sides of the springform pan.',
          'Bake for 1 hour and 15 minutes, or until the center is almost set.',
          'Turn off oven and let cake cool in oven with the door closed for 1 hour. Remove from oven and water bath. Cool completely on wire rack. Refrigerate for at least 4 hours before serving.',
      ],
      isPaid: true,
      price: 28.00,
      rating: 4.9,
      reviews: 95,
  },
  {
      id: 'rec_4',
      productId: 'prod_6',
      name: 'Moist & Flavorful Carrot Cake Recipe',
      description: 'A free recipe for the best carrot cake you will ever make. Perfectly spiced and incredibly moist.',
      ingredients: [
          { name: 'All-purpose flour', quantity: '2 cups' },
          { name: 'Baking soda', quantity: '2 tsp' },
          { name: 'Ground cinnamon', quantity: '2 tsp' },
          { name: 'Salt', quantity: '1/2 tsp' },
          { name: 'Large eggs', quantity: '3' },
          { name: 'Granulated sugar', quantity: '2 cups' },
          { name: 'Vegetable oil', quantity: '3/4 cup' },
          { name: 'Unsweetened applesauce', quantity: '3/4 cup' },
          { name: 'Vanilla extract', quantity: '2 tsp' },
          { name: 'Grated carrots', quantity: '3 cups' },
          { name: 'Chopped walnuts or pecans', quantity: '1 cup' },
      ],
      instructions: [
          'Preheat oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.',
          'In a medium bowl, whisk together flour, baking soda, cinnamon, and salt.',
          'In a large bowl, beat the eggs. Add sugar, oil, applesauce, and vanilla; beat until well combined.',
          'Add the dry ingredients to the wet ingredients and mix until just combined. Do not overmix.',
          'Stir in the grated carrots and nuts.',
          'Pour batter evenly into the prepared pans.',
          'Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.',
          'Let cool in pans for 10 minutes before inverting onto wire racks to cool completely before frosting.',
      ],
      isPaid: false,
      price: 0,
      rating: 4.7,
      reviews: 180,
  }
];

export const mockOrders: Order[] = [
  { id: 'ORD-1024', date: '2024-07-20', status: 'isDone', itemsSummary: 'Red Velvet Cupcakes (x1)', total: 24.00 },
  { id: 'ORD-1023', date: '2024-07-18', status: 'inDelivery', itemsSummary: 'Classic Cheesecake (x1)', total: 165.00 },
  { id: 'ORD-1022', date: '2024-07-18', status: 'inCreation', itemsSummary: 'Chocolate Chip Cookies (x2)', total: 24.00 },
  { id: 'ORD-1021', date: '2024-07-17', status: 'Accepted', itemsSummary: 'Sourdough Bread (x1)', total: 30.00 },
  { id: 'SO-1721511674296', date: '2024-07-16', status: 'Pending', itemsSummary: 'Special Request: Cake', total: 0.00 },
  { id: 'ORD-1019', date: '2024-07-15', status: 'Cancelled', itemsSummary: 'Vegan Oatmeal Cookies (x1)', total: 15.00 },
]
